#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════
//  scripts/icons-stage1.mjs — Icon 系统 Stage 1 一次性迁移
//  1) 15 个 legacy inline SVG → sprite <use>（分类计数断言）
//  2) 注入 #app-sprite（Lucide 0.525.0 · ISC + 3 枚合规 custom）
//  3) CSS：.ic 体系 + 尺寸/shape token；删除 .fab 死家族与散装 svg 规则
//  4) auth-eye 切换升级为 use href 互换（eye/eye-off）
//  每步带唯一性断言；任何断言失败即中止且不写文件。
// ═══════════════════════════════════════════════════════════════════
import { readFileSync, writeFileSync } from 'node:fs'

const FILE = 'index.html'
const html0 = readFileSync(FILE, 'utf8')
let html = html0
const stripNodeIds = (s) => s.replace(/ data-page-node-id="[^"]*"/g, '')

// ── 1. 用法替换（按路径内容分类） ────────────────────────────────
const MAP = [
  [/M12 7\.5V12l3 2/, 'i-clock', 20, 'lucide'],
  [/M8 10h8M8 14h5/, 'i-plan', 20, 'custom'],
  [/M5 19V11M12 19V5M19 19v-6/, 'i-progress', 20, 'custom'],
  [/M5\.5 19\.5c1\.2/, 'i-me', 20, 'custom'],
  [/M12 5v14M5 12h14/, 'i-plus', 20, 'lucide'],
  [/M2\.5 12s3\.5-6\.5/, 'i-eye', 20, 'lucide-spec'],
  [/M15 5l-7 7 7 7/, 'i-chevron-left', 16, 'lucide'],
  [/M5 12h14M13 6l6 6-6 6/, 'i-arrow-right', 16, 'lucide'],
  [/M5 12\.5l4\.5/, 'i-check', 12, 'lucide-spec'],
]
const EXPECT = { 'i-clock': 1, 'i-plan': 1, 'i-progress': 1, 'i-me': 1, 'i-plus': 1,
  'i-eye': 1, 'i-chevron-left': 7, 'i-arrow-right': 1, 'i-check': 1 }
const counts = {}, customInner = {}
let replaced = 0, unknown = 0

html = html.replace(/<svg viewBox="0 0 24 24"[^>]*>(?:(?!<\/svg>)[\s\S])*?<\/svg>/g, (m) => {
  for (const [re, id, size] of MAP) {
    if (re.test(m)) {
      counts[id] = (counts[id] || 0) + 1
      replaced++
      if (MAP.find(x => x[1] === id)[3] === 'custom') customInner[id] = m.replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '')
      return `<svg class="ic ic-${size}" aria-hidden="true"><use href="#${id}"></use></svg>`
    }
  }
  unknown++
  return m
})

let bad = []
for (const [id, n] of Object.entries(EXPECT)) if (counts[id] !== n) bad.push(`${id}: ${counts[id] || 0}/${n}`)
if (unknown || bad.length) {
  console.error('FAIL 用法分类不符 → unknown:', unknown, 'counts:', bad)
  process.exit(1)
}
console.log(`[ok] 用法替换 ${replaced}/15；分类`, JSON.stringify(counts))

// ── 2. 注入 sprite（body 开标签之后） ───────────────────────────
const LUCIDE = {
  'i-clock': '<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',
  'i-plus': '<path d="M5 12h14"/><path d="M12 5v14"/>',
  'i-check': '<path d="M20 6 9 17l-5-5"/>',
  'i-chevron-left': '<path d="m15 18-6-6 6-6"/>',
  'i-arrow-right': '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
  'i-eye': '<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/>',
  'i-eye-off': '<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"/><path d="M14.084 14.158a3 3 0 0 1-4.242-4.242"/><path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"/><path d="m2 2 20 20"/>',
}
const SYMBOLS = []
for (const [id, n] of Object.entries(EXPECT)) {
  const src = customInner[id]
    ? stripNodeIds(customInner[id])
    : LUCIDE[id]
  if (!src) { console.error('FAIL 缺少 symbol 源:', id); process.exit(1) }
  SYMBOLS.push(`  <symbol id="${id}" viewBox="0 0 24 24">${src}</symbol>`)
}
const SPRITE = `<!-- ICONS:BEGIN · generated by scripts/sync-icons.mjs · source: lucide-static 0.525.0 (ISC) + custom(compliant) -->
<svg id="app-sprite" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">
${SYMBOLS.join('\n')}
</svg>
<!-- ICONS:END -->`

const bodyTag = html.match(/<body[^>]*>/)
if (!bodyTag || bodyTag.length !== 1) { console.error('FAIL body 标签不唯一'); process.exit(1) }
html = html.replace(bodyTag[0], bodyTag[0] + '\n' + SPRITE)

// ── 3. CSS：token + .ic 体系 + 旧规则换轨/删除 ──────────────────
const mustReplace = (re, to, label, expect = 1) => {
  const hits = (html.match(re) || []).length
  if (hits !== expect) { console.error(`FAIL ${label}: 命中 ${hits}，期望 ${expect}`); process.exit(1) }
  html = html.replace(re, to)
  console.log(`[ok] ${label}`)
}
mustReplace(/--sp-8: 64px;/,
  `--sp-8: 64px;
  /* Icon 尺寸（七档）/ stroke（三档：1.75 small · 2 default · 2.25 large）*/
  --ic-12: 12px; --ic-16: 16px; --ic-18: 18px; --ic-20: 20px; --ic-24: 24px; --ic-28: 28px; --ic-32: 32px;`,
  'icon 尺寸 token')
mustReplace(/\/\* ═+ Calendar 四色语义 ═+ \*\//,
  `/* ═══════════ Icon 系统（Stage1）：sprite + 单一 family（Lucide, ISC）═══════════ */
.ic { width: var(--ic-20); height: var(--ic-20); fill: none; stroke: currentColor;
  stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; flex-shrink: 0; }
.ic-12 { width: var(--ic-12); height: var(--ic-12); stroke-width: 1.75; }
.ic-16 { width: var(--ic-16); height: var(--ic-16); stroke-width: 1.75; }
.ic-18 { width: var(--ic-18); height: var(--ic-18); }
.ic-24 { width: var(--ic-24); height: var(--ic-24); }
.ic-28 { width: var(--ic-28); height: var(--ic-28); stroke-width: 2.25; }
.ic-32 { width: var(--ic-32); height: var(--ic-32); stroke-width: 2.25; }

/* ═══════════ Calendar 四色语义 ═══════════ */`,
  '.ic 体系')
mustReplace(/\.tl-check svg \{[^}]+\}/,
  '.tl-check .ic { width: var(--ic-12); height: var(--ic-12); stroke: #fff; stroke-width: 1.75; opacity: 0; transform: scale(.5); transition: all .18s var(--ease); }',
  '.tl-check')
mustReplace(/\.tl-row\.done \.tl-check svg \{[^}]+\}/,
  '.tl-row.done .tl-check .ic { opacity: 1; transform: scale(1); }',
  '.tl-row.done .tl-check')
mustReplace(/\.tl-add svg \{[^}]+\}/, '/* .tl-add 尺寸/描边由 .ic 基类承载 */', '.tl-add svg→删除')
mustReplace(/\.myday \.go svg \{[^}]+\}/, '.myday .go .ic { width: var(--ic-16); height: var(--ic-16); }', '.myday .go')
mustReplace(/\.tab svg \{[^}]+\}/, '.tab .ic { width: var(--ic-20); height: var(--ic-20); }', '.tab svg')
mustReplace(/\.tab\.on svg \{[^}]+\}/, '/* tab 激活态强调 = 颜色（primary/tertiary），不加重描边 */', '.tab.on svg→删除')
mustReplace(/\.auth-eye svg \{[^}]+\}/, '.auth-eye .ic { width: var(--ic-20); height: var(--ic-20); }', '.auth-eye')
mustReplace(/\n\.fab \{[^}]+\}/, '', '.fab 死规则删除')
mustReplace(/\n\.fab svg \{[^}]+\}/, '', '.fab svg 死规则删除')
mustReplace(/\n\.phone\[data-mode="dark"\] \.fab \{[^}]+\}/, '', 'dark .fab 死规则删除')
mustReplace(/\n\.phone\[data-mode="dark"\] \.fab svg \{[^}]+\}/, '', 'dark .fab svg 死规则删除')

// ── 4. auth-eye 切换 → use href 互换 ────────────────────────────
mustReplace(/p\.type = p\.type === 'password' \? 'text' : 'password';/,
  `p.type = p.type === 'password' ? 'text' : 'password';
    const u = document.querySelector('#auth-eye use');
    if (u) u.setAttribute('href', p.type === 'password' ? '#i-eye' : '#i-eye-off');`,
  'auth-eye use 切换')

// ── 5. 终检并写回 ───────────────────────────────────────────────
if (!html.includes('id="app-sprite"')) { console.error('FAIL sprite 未注入'); process.exit(1) }
if ((html.match(/viewBox="0 0 24 24"/g) || []).length !== 10) {
  console.error('FAIL sprite symbol 数应为 10（9 用途 + eye-off 切换）'); process.exit(1)
}
writeFileSync(FILE, html)
console.log('[done] index.html 已写回；净变化', html.length - html0.length, '字符')
