#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════
//  scripts/sync-icons.mjs — 刷新 legacy.html 内的 Lucide sprite
//
//  用法：node scripts/sync-icons.mjs
//  行为：从 unpkg 的 lucide-static 固定版本拉取 ICONS 表中的图标，
//        重写 legacy.html 中 <!-- ICONS:BEGIN/END --> 之间的 symbol 块。
//  规则：source=custom 的 symbol（i-plan / i-progress / i-me）不受影响，
//        永远保留本地几何（已按 24 网格 / 2px 规范手工校准）。
//  升级版本：改 LUCIDE_VER 后重跑；跑完必须重跑全套测试。
// ═══════════════════════════════════════════════════════════════════
import { readFileSync, writeFileSync } from 'node:fs'

const LUCIDE_VER = '0.525.0'
const FILE = 'legacy.html'
// id → lucide-static 图标名（custom 的不在此表，见 CUSTOM）
const ICONS = {
  'i-clock': 'clock',
  'i-plus': 'plus',
  'i-check': 'check',
  'i-chevron-left': 'chevron-left',
  'i-arrow-right': 'arrow-right',
  'i-eye': 'eye',
  'i-eye-off': 'eye-off',
}

const html = readFileSync(FILE, 'utf8')
const m = html.match(/<!-- ICONS:BEGIN[\s\S]*?<!-- ICONS:END -->/)
if (!m) { console.error('[sync] FAIL: 找不到 ICONS:BEGIN/END 标记'); process.exit(1) }
const oldBlock = m[0]

// 保留 custom symbol（本地几何，不随上游变化）
const customs = [...oldBlock.matchAll(/<symbol id="(i-(?:plan|progress|me))"[^>]*>([\s\S]*?)<\/symbol>/g)]
const customMap = Object.fromEntries(customs.map(c => [c[1], c[2]]))
if (Object.keys(customMap).length !== 3) {
  console.error('[sync] FAIL: custom symbol 应为 3 枚（plan/progress/me），实得', Object.keys(customMap).length)
  process.exit(1)
}

const strip = (svg) => svg
  .replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '')
  .replace(/ stroke="currentColor"/g, '').replace(/ stroke-width="2"/g, '')
  .replace(/ stroke-linecap="round"/g, '').replace(/ stroke-linejoin="round"/g, '')
  .replace(/\n\s*/g, '').trim()

const fetchIcon = async (name) => {
  const res = await fetch(`https://unpkg.com/lucide-static@${LUCIDE_VER}/icons/${name}.svg`)
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`)
  return strip(await res.text())
}

const all = { ...ICONS }
for (const [id, name] of Object.entries(all)) all[id] = await fetchIcon(name)

const lines = [
  ...Object.entries(all).map(([id, inner]) => `  <symbol id="${id}" viewBox="0 0 24 24">${inner}</symbol>`),
  ...Object.entries(customMap).map(([id, inner]) => `  <symbol id="${id}" viewBox="0 0 24 24">${inner}</symbol>`),
]
const next = html.replace(
  /<!-- ICONS:BEGIN[\s\S]*?<!-- ICONS:END -->/,
  `<!-- ICONS:BEGIN · generated by scripts/sync-icons.mjs · source: lucide-static ${LUCIDE_VER} (ISC) + custom(compliant) -->\n<svg id="app-sprite" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">\n${lines.join('\n')}\n</svg>\n<!-- ICONS:END -->`)
writeFileSync(FILE, next)
console.log(`[sync] 完成：lucide ${Object.keys(ICONS).length} 枚 + custom ${Object.keys(customMap).length} 枚；净变化 ${next.length - html.length} 字符`)
